### ISSUE TITLE
Support multiple endpoints within a single Streams application.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/endpoint-monitor#10]
While a common case is for all rest operators to be fused together, this should not be a requirement, so we could have:

* injection with context path `sensors` on ip 172.0.0.2 and port 32255
* tuple view with context path `state` on ip 172.0.0.4 and port 38321

Since the lead in path is the same, we need entries that are logically

`streams/job/123/sensors --> 172.0.0.2:32255/sensors`
`streams/job/123/state --> 172.0.0.4: 38321/state `

May need changes so that the context path is visible through metrics, though maybe the existing REST api to get the info is enough?

Note this is not the case where a single logical rest operator is replicated using UDP, e.g. multiple injection operators for performance that feed into the same logical stream.

**Comment by ddebrunner** [comment]
How to handle `ports/info` in this case? Ie. there are two sets of ports being exposed so how to have an external client discover them.

Need to verify the specific meta-data available through the context path.

**Comment by joergboe** [comment]
How can a metric reflect a context path? A metric is always a int, not a string.
I propose to extend the inetserver Operators with an boolean parameter 'contentPathPrefix'
if turned on, the operator prefixes the content path with the job name.

**Comment by joergboe** [comment]
UDP for inetserver operators:

- **Case 1**: all inetserver operators of the same kind **share** the pe:
The application developer must make sure that the context pathes are distinguishable (e. g. by extending the channel number to context path. Then all operators share a single jetty instance notably the thread pool. -> Makes no sense, because no performance improvement can be expected.
We should **not support** this config.

Case 2:  all inetserver operators of the same kind are placed in a separate pe:
Each jetty instances has an own ip-address/portnumber. If this is used behind the reverse-proxy, the proxy must support any kind of distribution method.
We should not support this in the first version.

**Comment by joergboe** [comment]
- jobName**1**: context path **TupleInject** on ip 172.0.0.2 and port 32255
- jobName**1**: context path **TupleView** on  ip     172.0.0.2 and port 32255 (shared jetty)
- jobName**1**: context path **TupleView2** on ip      172.0.0.4 and port 38321 (separate jetty)
- jobName**2**: context path **TupleInject** on ip 172.0.0.2 and port 32256

Proposal mapping:
jobName1/TupleInject --> 172.0.0.2:32255/TupleInject
jobName1/TupleView     --> 172.0.0.2:32255/TupleView
jobName1/TupleView2    -->  172.0.0.4:38321/TupleView2
jobName2/TupleInject --> 172.0.0.2:32256/TupleInject

Note: We can not support the context path parameter of the internetserver operators, because it is not known externally. We must use the default context path the operator-name.

Enhancement:
provide a context -> operatorname mapping to the ngix proxy

**Comment by joergboe** [comment]
Probably we can provide a special uri in the internetserver ServletEngine, that provides the list of the registered contexts.

**Comment by ddebrunner** [comment]
> How can a metric reflect a context path?
By creating a metric with a name including the context path, e.g. `path.mycontextpath`

**Comment by ddebrunner** [comment]
> Note: We can not support the context path parameter of the internetserver operators, because it is not known externally.

Actually it is, since it's available through the URL path `ports/info`.

**Comment by ddebrunner** [comment]
> Probably we can provide a special uri in the internetserver ServletEngine, that provides the list of the registered contexts.

Already exists, at least for ports

**Comment by ddebrunner** [comment]
Fixed.
